### ISSUE TITLE
Error uploading base64 media to Twitter: media type unrecognised

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [overlapshow/overlap-twitter-bot#2]
Image from URL converted to base64 via the base64-img module fails to upload to Twitter. Running the conversion independently confirms conversion takes place, base64 image formatted as follows:
```
data:image/jpeg;base64,/9j/4SrXRXhpZgAASUkqAAgAAAAIAA8BAgASAAAAbgAAABABAgALAAAAgAAAA...
```

Full Twitter error:
```
{ Error: media type unrecognized.
    at Object.exports.makeTwitError (/Users/pdandy/Dev/overlap-twitter-bot/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/Users/pdandy/Dev/overlap-twitter-bot/node_modules/twit/lib/twitter.js:328:25)
    at Request.<anonymous> (/Users/pdandy/Dev/overlap-twitter-bot/node_modules/twit/lib/twitter.js:348:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/Users/pdandy/Dev/overlap-twitter-bot/node_modules/request/request.js:1091:12)
    at Gunzip.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'media type unrecognized.',
  code: null,
  allErrors: 
   [ { request: '/1.1/media/upload.json',
       error: 'media type unrecognized.' } ],
  twitterReply: 
   { request: '/1.1/media/upload.json',
     error: 'media type unrecognized.' },
  statusCode: 400 
}```

**Comment by hayleigh-dot-dev** [comment]
Relevant code:

```javascript
function postTweet(twitter, ID, username, artist) {
  var response    = '@'+username+' '+makeResponseFromArtist(artist),
      mediaURL    = getMediaURLFromArtist(artist),
      mediaID     = uploadMedia(twitter, mediaURL);

  twitter.post('statuses/update', {
    status                : response,
    in_reply_to_status_id : ID,
    media_ids             : mediaID
  }, function(err, data, response) {
    if(err) {
      // console logs...
    } else {
      // console logs...
    }
  });
}

function uploadMedia(twitter, mediaURL) {
  var imageStr;
  
  base64Img.requestBase64(mediaURL, function(err, res, body) {
    if (!err) {
      var imageData = body.slice(body.indexOf(',');

      twitter.post('media/upload', {
        media_data: imageData[1]
      }, function(err, data, response) {
        if (!err) {
          imageStr = data.media_id_str;
        } else {
          imageStr = null;
        }
      });
    } else {
      // console logs...
    }
  });
  
  return imageStr;
}
```

I have a sneaking suspicion that either:
- I need to strip `data:image/jpeg;base64,` from the data OR
- `.requestBase64` is synchronous and we're posting the status before the request has finished.

Will report back soon.

**Comment by hayleigh-dot-dev** [comment]
Snooping at @pouretrebelle 's maze-bot code confirms its an async thing. Trying `deasync` node module now.

**Comment by hayleigh-dot-dev** [comment]
Reporting back. Fixed a bug here:
```javascript
twitter.post('media/upload', {
  media_data: imageData[1]
}
```
Corrections:
```javascript
media_data: imageData
```
Base64 image now uploads, but tweet is sent off before we do. Console logs are:
```
Tweet recieved {
  username: pdAndyUK
  tweet: @overlapshow tell me about howard and saskia
}
Encoding media to base64...
Encoding media to base64...
Reply posted! {
  status: [object Object]
  in_reply_to_status_id: 884840132897116160
}
Reply posted! {
  status: [object Object]
  in_reply_to_status_id: 884840132897116160
}
Uploading base64 media to twitter...
Uploading base64 media to twitter...
Media ID string {
  undefined
}
Media ID string {
  undefined
}
```

**Comment by hayleigh-dot-dev** [comment]
Taken the lazy route and stored all the images locally.
